<li type="guoji" subtype="" style="padding: 10px 10px 0 10px;"><a href="view.php?aid=[field:id/]" data-url="[field:arcurl/]"><div class="lb-text ">[field:title/]</div><div class="bigimg" style="background:url([field:litpic/]);background-position:center;background-size: 100%"></div>
<!-- <div class="statu"><div class="lb-time">
 <span class="hot_label space">热门</span>
 </div>
 <div class="lb-resource">中国新闻网</div></div>--></a></li>