<?php
$z[0]=Array("field","",23,42);
$z[0][4]=array();
$z[0][4]['name']="title";
$z[1]=Array("global","",43,69);
$z[1][4]=array();
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",189,211);
$z[2][4]=array();
$z[2][4]['name']="keywords";
$z[3]=Array("field","",251,302);
$z[3][4]=array();
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("global","",638,670);
$z[4][4]=array();
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("include","",736,781);
$z[5][4]=array();
$z[5][4]['filename']="style_header_m.htm";
$z[6]=Array("productimagelist","\r\n             <img src=\"[field:imgsrc/]\" width=\"100%\" style=\"padding: 10px 10px 0 10px;width: calc(100% - (10px) * 2);\"> \r\n          \r\n",992,1175);
$z[6][4]=array();
$z[7]=Array("type","<a href=\"list.php?tid=[field:id/]\" style=\"margin:0 ; padding:0;text-align:center;\">返回列表页</a>",1645,1770);
$z[7][4]=array();
$z[8]=Array("global","",1985,2014);
$z[8][4]=array();
$z[8][4]['name']="cfg_shoujidibu";
$z[9]=Array("global","",2032,2059);
$z[9][4]=array();
$z[9][4]['name']="cfg_basehost";
$z[10]=Array("global","",2195,2221);
$z[10][4]=array();
$z[10][4]['name']="cfg_webname";

?>