<li class="img-txt-item clearfix"> <a class="img fl" href="[field:arcurl/]" target="_blank" title="[field:title/]"> <img class="animation" src="[field:picname function='thumb(@me,112,84,true)'/]" alt="[field:title/]" width="112" height="84"> </a>
            <div class="txt">
              <p class="topic"><a href="[field:arcurl/]" target="_blank" title="[field:title/]">[field:title/]</a></p>
              <p class="from mt5">来源：[field:source/]</p>
              <p class="time">[field:pubdate function=MyDate('m-d',@me)/]</p>
            </div>
          </li>