<?php
$z[0]=Array("field","",23,42);
$z[0][4]=array();
$z[0][4]['name']="title";
$z[1]=Array("global","",43,69);
$z[1][4]=array();
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",189,218);
$z[2][4]=array();
$z[2][4]['name']="keywords";
$z[3]=Array("field","",258,316);
$z[3][4]=array();
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("global","",654,686);
$z[4][4]=array();
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("include","",743,788);
$z[5][4]=array();
$z[5][4]['filename']="style_header_m.htm";
$z[6]=Array("list","\r\n            <section class=\"middle_mode has_action\"><div class=\"one-px-border\"></div><a href=\"view.php?aid=[field:id/]\" class=\"article_link clearfix \"><div class=\"desc\"><h3 class=\"dotdot line3 image-margin-right\">[field:title/]</h3><div class=\"item_info\"><span class=\"time\">[field:pubdate function=\"GetDateMK(@me)\"/]</span></div></div><div class=\"list_img_holder\" style=\"background: none;\"><img src=\"[field:litpic/]\"></div></a></section>\r\n          ",1044,1532);
$z[6][4]=array();
$z[6][4]['pagesize']="10";
$z[7]=Array("type","<a href=\"list.php?tid=[field:id/]\" style=\"margin:0 ; padding:0;text-align:center;\">返回列表页</a>",2020,2145);
$z[7][4]=array();
$z[8]=Array("global","",2200,2229);
$z[8][4]=array();
$z[8][4]['name']="cfg_shoujidibu";
$z[9]=Array("global","",2247,2274);
$z[9][4]=array();
$z[9][4]['name']="cfg_basehost";
$z[10]=Array("global","",2410,2436);
$z[10][4]=array();
$z[10][4]['name']="cfg_webname";

?>