<?php
$z[0]=Array("flink","\r\n[field:link/]\r\n",90,167);
$z[0][4]=array();
$z[0][4]['row']="24";
$z[0][4]['titlelen']="24";
$z[0][4]['typeid']="1";
$z[1]=Array("global","",320,343);
$z[1][4]=array();
$z[1][4]['name']="cfg_dibu";
$z[2]=Array("type","<a title=\"\" target=\"_blank\" href=\"[field:typeurl/]\">[field:typename/]</a>",352,460);
$z[2][4]=array();
$z[2][4]['typeid']="21";
$z[3]=Array("global","",467,494);
$z[3][4]=array();
$z[3][4]['name']="cfg_indexurl";

?>